version: "3"
services:
  db:
    container_name: pg-prod
    image: postgres
    networks:
      - curso-network
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres

  poc-cep:
    container_name: pock-curso
    image: victormacedo400/pock-curso
    networks:
      - curso-network
    ports:
      - 8080:8080
    environment:
      - DB_HOST=db
    depends_on:
      - db

networks:
  curso-network: